apiVersion: v1
kind: Service
metadata:
  name: sd-api-service
  namespace: sd-api
spec:
  ports:
    - port: 80
      name: tcp-80
      protocol: TCP
      targetPort: 80
  selector:
    app: sd-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sd-api-ingress
  namespace: sd-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/issuer: "#{{CERT_ISSUER}}#"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  tls:
    - hosts:
        - "#{{APP_DOMAIN}}#"
      secretName: "#{{APP_CERT_SECRET}}#"
  rules:
    - host: "#{{APP_DOMAIN}}#"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sd-api-svc
                port:
                  number: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sd-api-ingress
  namespace: sd-api
data:
  use-http2: "true"
