apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-api-deployment
  namespace: sd-api
  labels:
    app: sd-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sd-api
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: sd-api
    spec:
      serviceAccountName: sd-api-service
      containers:
        - name: sd-api
          image: psxycrsharedacrstockdatamgnt.azurecr.io/environments/application/api:dev
          resources:
            requests:
              memory: "1024M"
              cpu: "0.2"
            limits:
              memory: "2048M"
              cpu: "1"
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: DATABASE_URL
            - name: STOCK_DATA_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_ACCOUNT_NAME
            - name: FLAG_SMITH_ENVIRONMENT_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: FLAG_SMITH_ENVIRONMENT_KEY
            - name: STOCK_DATA_STORAGE_FILE_SYSTEM
              valueFrom:
                secretKeyRef:
                  name: backend-auth
                  key: STOCK_DATA_STORAGE_FILE_SYSTEM
          volumeMounts:
            - name: kv-secret-store
              mountPath: "/mnt/backend-auth"
              readOnly: true
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.azure.com/scalesetpriority"
                    operator: In
                    values:
                      - "spot"
      volumes:
        - name: kv-secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync"
